name: allure-report

on:
  release:
    types:
      - created
  push:
    branches-ignore:
      - '!master'

jobs:
  allure:
    name: Generate Allure Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Allure history
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          repository: simple-elf/allure-report-action
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from repo
        uses: ./action.yml
        #id: allure-report
        with:
          allure_results: allure-results
          #gh_pages: gh-pages
          #allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history