name: allure-report-pr

on:
  pull_request:
    types: [opened, reopened]

jobs:
  allure-pr:
    name: Check Allure Report Action on Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Allure Report action from repo
        uses: ./
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 1